### ISSUE TITLE
I would like to enhance my Node and React js skills and learn the appropriate frameworks for this project. 

### ISSUE THREAD

**Issue by isabellasteains** [nyu-software-engineering/fall-2019-chores#28]
- [x] Watch the MERN Stack tutorial
- [x] Refresh Node.js Skills
- [x] Refresh React.js Skills
- [x] Read Documentation on Express and MongoDB
- [x] Research Appropriate Frameworks/IDEs
- [x] Research Relevant APIs

**Comment by Ulbert** [comment]
The MERT stack huh? 🤔🤔🤔
